services:
  client-config2:
    build:
      context: config2
      dockerfile: Dockerfile.config2
    image: project1-client-config2:1
    working_dir: /lab
    command: [sleep, infinity]
    networks:
      - mongo-net
